<a href="https://colab.research.google.com/github/Leo-Monarrez/BOSTON/blob/main/BOSTON_POLY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import model_selection
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
file_url = 'https://raw.githubusercontent.com/Leo-Monarrez/BOSTON/main/housing.csv'
df = pd.read_csv(file_url)

features = np.array(df.drop('MEDV', 1))
features

<ipython-input-16-6bcf6ddef5f1>:10: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  features = np.array(df.drop('MEDV', 1))


array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [17]:
label = np.array(df['MEDV'])
label

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [18]:
scaled_features = preprocessing.scale(features)
scaled_features

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [19]:
poly_1_scaled_features = PolynomialFeatures(degree=1).fit_transform(scaled_features)
poly_1_scaled_features

array([[ 1.        , -0.41978194,  0.28482986, ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [ 1.        , -0.41733926, -0.48772236, ..., -0.30309415,
         0.44105193, -0.49243937],
       [ 1.        , -0.41734159, -0.48772236, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [ 1.        , -0.41344658, -0.48772236, ...,  1.17646583,
         0.44105193, -0.98304761],
       [ 1.        , -0.40776407, -0.48772236, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [ 1.        , -0.41500016, -0.48772236, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [20]:
poly_2_scaled_features = PolynomialFeatures(degree=2).fit_transform(scaled_features)
poly_2_scaled_features

array([[ 1.        , -0.41978194,  0.28482986, ...,  0.19452681,
        -0.47437883,  1.15683427],
       [ 1.        , -0.41733926, -0.48772236, ...,  0.19452681,
        -0.21719133,  0.24249653],
       [ 1.        , -0.41734159, -0.48772236, ...,  0.15715436,
        -0.47917217,  1.46102192],
       ...,
       [ 1.        , -0.41344658, -0.48772236, ...,  0.19452681,
        -0.43357505,  0.9663826 ],
       [ 1.        , -0.40776407, -0.48772236, ...,  0.16259032,
        -0.34891116,  0.74874691],
       [ 1.        , -0.41500016, -0.48772236, ...,  0.19452681,
        -0.29508947,  0.44763905]])

In [21]:
poly_3_scaled_features = PolynomialFeatures(degree=3).fit_transform(scaled_features)
poly_3_scaled_features

array([[ 1.        , -0.41978194,  0.28482986, ..., -0.2092257 ,
         0.51022399, -1.24424733],
       [ 1.        , -0.41733926, -0.48772236, ..., -0.09579266,
         0.10695356, -0.11941484],
       [ 1.        , -0.41734159, -0.48772236, ..., -0.18995678,
         0.57918853, -1.76597723],
       ...,
       [ 1.        , -0.41344658, -0.48772236, ..., -0.19122911,
         0.42622491, -0.9500001 ],
       [ 1.        , -0.40776407, -0.48772236, ..., -0.14068967,
         0.3019134 , -0.64789192],
       [ 1.        , -0.41500016, -0.48772236, ..., -0.13014978,
         0.19743207, -0.29949664]])

In [22]:
poly_1_features_train, poly_1_features_test, poly_label_train, poly_label_test = model_selection.train_test_split(poly_1_scaled_features, label, test_size=0.1, random_state=8)
poly_2_features_train, poly_2_features_test, poly_label_train, poly_label_test = model_selection.train_test_split(poly_2_scaled_features, label, test_size=0.1, random_state=8)
poly_3_features_train, poly_3_features_test, poly_label_train, poly_label_test = model_selection.train_test_split(poly_3_scaled_features, label, test_size=0.1, random_state=8)
model_1 = linear_model.LinearRegression()
model_1.fit(poly_1_features_train, poly_label_train)
model_1_score_train = model_1.score(poly_1_features_train, poly_label_train)
model_1_score_train

0.7473028975901506

In [23]:
model_1_score_test = model_1.score(poly_1_features_test, poly_label_test)
model_1_score_test

0.6806043226089127

In [24]:
model_2 = linear_model.LinearRegression()
model_2.fit(poly_2_features_train, poly_label_train)
model_2_score_train = model_2.score(poly_2_features_train, poly_label_train)
model_2_score_train

0.9330693967960804

In [25]:
model_2_score_test = model_2.score(poly_2_features_test, poly_label_test)
model_2_score_test

0.831716044700928

In [26]:
model_3 = linear_model.LinearRegression()
model_3.fit(poly_3_features_train, poly_label_train)
model_3_score_train = model_3.score(poly_3_features_train, poly_label_train)
model_3_score_train

1.0

In [27]:
model_3_score_test = model_3.score(poly_3_features_test, poly_label_test)
model_3_score_test

-401403.0057434383

In [28]:
model_1_prediction = model_1.predict(poly_1_features_test)
model_2_prediction = model_2.predict(poly_2_features_test)
model_3_prediction = model_3.predict(poly_3_features_test)

df_prediction = pd.DataFrame(poly_label_test)
df_prediction.rename(columns = {0:'label'}, inplace = True)
df_prediction['model_1_prediction'] = pd.DataFrame(model_1_prediction)
df_prediction['model_2_prediction'] = pd.DataFrame(model_2_prediction)
df_prediction['model_3_prediction'] = pd.DataFrame(model_3_prediction)
df_prediction

label  model_1_prediction  model_2_prediction  model_3_prediction
0    18.5           19.275384           19.977051         -259.054600
1    12.7           11.352219           14.552490           87.875675
2    21.9           38.126044           32.001953       -36406.661570
3    22.0           27.162814           26.768799         -511.557087
4    50.0           40.624018           46.439453         5874.001927
5    36.2           27.662116           26.188477           54.283615
6    16.5           11.049223           17.250488        -1238.718633
7    32.4           36.347036           31.982666         2609.573010
8    24.6           29.050437           27.279785          349.444900
9    50.0           34.860743           54.644531        -1662.756207
10   13.9           13.366888           15.775391         -204.077260
11   11.9            7.881704           17.337158          -17.159728
12   16.2           15.370780           15.883301         -345.569863
13   21.4           24.536537           22.651855          873.680918
14   14.1           16.128191           14.394287           31.564534
15   22.8           28.689566           26.984619          -10.088021
16   20.2           22.779223           22.465576           42.288633
17   20.6           22.288300           21.322510          230.757811
18   21.7           20.835560           24.330566        -3131.829504
19    8.5            7.186754            7.299072          -44.859809
20   19.7           21.072671           21.427246          534.425933
21   24.7           25.223958           24.432861        -4882.722773
22   24.0           30.167687           25.096191        -2567.519433
23   31.7           33.206407           35.120605          -84.310125
24   28.6           28.204143           30.093994         1174.855389
25   33.4           35.657585           38.063721          141.325038
26    7.4            5.529353            8.649414          -38.796822
27   14.8           14.691199           16.113525         -249.469463
28   25.0           25.250865           22.820557           58.579946
29   17.0           22.952740           14.325928        10687.414140
30   31.0           34.582109           33.350586         1932.138392
31   12.6           18.424941           14.093262           11.950413
32   19.4           19.796996           18.635986          -18.840710
33   11.9           22.560512           18.182617          -20.144384
34   24.8           25.205379           24.105469         -583.761896
35   23.7           27.054021           28.562012           25.869664
36   29.0           32.179122           33.633057          659.511138
37   21.6           25.544606           22.599854          123.992075
38   14.3           14.230923           17.052734         -633.521177
39   11.5           14.327703           14.977295            2.378731
40   21.7           22.117403           19.166992        -2147.289155
41   20.7           21.674100           23.991211         -322.985687
42   50.0           35.940179           41.926025          177.784691
43   33.8           35.010364           34.703613          -65.140198
44   33.0           23.220547           30.865723         3643.017057
45   19.6           18.811559           16.222168         4916.509963
46   17.8           20.050009           29.571777       -17254.005567
47   21.8           21.117315           18.899170          -23.014672
48   19.4           25.725392           19.904053        -1195.401569
49   29.6           24.591664           24.190918         -486.627185
50   17.1           20.027097           18.745117          398.770064